# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZamsbbSCpaHM9o30BWotJwB4_g6x1F3q
"""



# from menu import Menu # This line is not needed as Menu is defined in another cell

def kitap_ekle():
    print("Kitap ekleme fonksiyonu çalıştı.")

def kitaplari_listele():
    print("Kitap listeleme fonksiyonu çalıştı.")

def kitap_ara():
    print("Kitap arama fonksiyonu çalıştı.")

if __name__ == "__main__":
    menu = Menu("📖 Kitaplık Uygulaması Menüsü")
    menu.add_option("Kitap Ekle", kitap_ekle) # Corrected typo here
    menu.add_option("Kitapları Listele", kitaplari_listele)
    menu.add_option("Kitap Ara", kitap_ara)
    menu.show()