# -*- coding: utf-8 -*-
"""menu

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZamsbbSCpaHM9o30BWotJwB4_g6x1F3q
"""



class Menu:
    def __init__(self, title="Ana Menü"):
        self.title = title
        self.options = []  # (menü adı, fonksiyon) çiftlerini tutar

    def add_option(self, name, function):
        """Menüye yeni bir seçenek ekler."""
        self.options.append((name, function))

    def show(self):
        """Menüyü gösterir ve kullanıcı seçimini yönetir."""
        while True:
            print(f"\n--- {self.title} ---")
            for i, (name, _) in enumerate(self.options, start=1):
                print(f"{i}. {name}")
            print(f"{len(self.options)+1}. Çıkış")

            secim = input("Seçiminiz: ")

            if not secim.isdigit():
                print("Lütfen geçerli bir sayı girin.")
                continue

            secim = int(secim)
            if secim == len(self.options) + 1:
                print("Programdan çıkılıyor...")
                break
            elif 1 <= secim <= len(self.options):
                func = self.options[secim - 1][1]
                func()
            else:
                print("Geçersiz seçim!")